theme: jekyll-theme-cayman
github:
  repository_url: https://alecstem.github.io/REUWebsite/
self:
  about: https://alecstem.github.io/REUWebsite/about
  home: https://alecstem.github.io/REUWebsite/
  view_project: https://alecstem.github.io/REUWebsite/view_project
  materials: https://alecstem.github.io/REUWebsite/materials
