theme: jekyll-theme-cayman
image: /Image/website_banner.jpg
github:
  repository_url: https://alecstem.github.io/REUWebsite/
self:
  about: https://alecstem.github.io/REUWebsite/about
  home: https://alecstem.github.io/REUWebsite/
  view_project: https://alecstem.github.io/REUWebsite/view_project
  research: https://alecstem.github.io/REUWebsite/research
  materials: https://alecstem.github.io/REUWebsite/materials
